### ISSUE TITLE
检测不到有人顶帖

### ISSUE THREAD

**Issue by jiajiaxd** [R-Josef/BBSToper#10]
本人服务器链接：https://www.mcbbs.net/thread-1124469-1-1.html
本人MCBBS个人资料页：https://www.mcbbs.net/home.php?mod=space&uid=1781182
使用了BBSToper 3.6.5 最新版本
如图，服务器内已经正确绑定了我的MCBBS
![image](https://user-images.githubusercontent.com/51043917/125185450-76513e00-e257-11eb-9cad-320f14ab47cf.png)
配置文件内已经正确配置本服ID
![image](https://user-images.githubusercontent.com/51043917/125185512-c92af580-e257-11eb-8d1a-60e61eeb9549.png)
我也已经顶帖
![image](https://user-images.githubusercontent.com/51043917/125185472-92ed7600-e257-11eb-88ad-1e945ef5385b.png)
但是插件就是检测不到我顶帖
![image](https://user-images.githubusercontent.com/51043917/125185478-9c76de00-e257-11eb-883d-767f55508c91.png)
后台没有任何报错，只有YUM的网络检测。但是没有对BBSToper进行拦截。
![image](https://user-images.githubusercontent.com/51043917/125185628-84538e80-e258-11eb-94f4-eb6dc341e76a.png)

**Comment by R-Josef** [comment]
Yum插件会阻止BBSToper联网，你可以卸载Yum试试，确定是Yum插件的问题后可以可以去Yum插件里面给BBSToper添加一个白名单。
