### ISSUE TITLE
有关插件重制

### ISSUE THREAD

**Issue by DreamVoid** [R-Josef/BBSToper#22]
我最近在开始优化BBSToper的代码（[见此](https://github.com/DreamVoid/BBSToper/tree/main)），也注意到了插件很久没有新代码提交了，不知道我重制完成后能否就用我的仓库以 BBSToper 4.0 的名义发布出去？直接提交到这个仓库的话我怕会出一些问题。

**Comment by R-Josef** [comment]
你好，谢谢你的关注，我有空看看你的代码，之后回复你的消息

**Comment by R-Josef** [comment]
抱歉回复晚了，代码我大概看了一下，数据库换成用连接池挺不错，其他的主要是细节上的东西，也挺好的。据这个插件的许可协议，你可以以BBSToper 4.0的名义或者其他任何名字发布，只需要遵循许可协议中写明的两个条件，但是我无法提供除此之外的任何保证或者背书，谢谢你的支持。
