### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by Policymaker23** [R-Josef/BBSToper#5]
1.请问能否设置顶帖奖励间隔，比如一个玩家顶帖后，另外一个玩家必须要在1小时后顶帖，才算做有效顶帖
2.请问能否设置顶帖时间限制,比如只有在早上8点到晚上10点的顶帖才有效

**Comment by R-Josef** [comment]
我不建议这样做，我知道如果玩家在凌晨顶贴或者跟着其他人连续顶贴之后，获得的收益很小，但是该大度的地方就不应该太计较得失。如果玩家在顶贴之后因为各种限制而导致没有获得奖励，会打消玩家顶贴的积极性。
另外关于深夜顶贴，我觉得既然深夜有人顶贴就说明是存在这种夜猫子深夜上网的，也许也能收获一些夜猫子新玩家。而且深夜顶贴的玩家肯定不如白天多，同样深夜顶贴的其他服主也很少，这恰巧可以保持一种平衡。
不过，我还是会考虑在新版本加上这个功能的。

**Comment by Policymaker23** [comment]
确实，开放深夜顶帖也是很不错的选择。连续顶帖设置奖励衰减并提示也许会对积极性的影响会小一点，毕竟大部分玩家的金粒都来之不易

**Comment by R-Josef** [comment]
好，我好好思考一下该怎么做

**Comment by R-Josef** [comment]
我换了一种思路，当一个玩家在距离上一个玩家顶贴之后达到设定的时间（有一定的时间没有人顶贴），那么就奖励玩家额外的激励奖励，这样听上去也好听很多，给玩家额外的奖励，而不是扣除了奖励，虽然实质上是一样的。我已经在最新的版本中加入了这个功能，另外我还加入了一个在休息日顶贴额外获得奖励的功能。
[BBSToper 3.6](https://github.com/R-Josef/BBSToper/releases/tag/3.6)
