### ISSUE TITLE
报错+无限给顶帖奖励

### ISSUE THREAD

**Issue by Xenon135** [R-Josef/BBSToper#6]
先感谢老铁写了这样一个好东西出来。
同为公益服管理员给你点赞！

## 简单描述

服务端版本 paperspigot 1.15.2 build 215 (因兼容问题等没有更新到最新版本)
BBSToper插件版本  3.6    从mcbbs直接下载
插件列表如有需要请再跟我联系

问题发生时间在2020年6月8日早上八九点左右
玩家在绑定、顶帖后发现顶帖奖励每隔几秒钟就发一次
明显不正常（玩家只顶帖一次）
伴随插件报错

### 服务器日志（含报错信息等）
https://paste.ubuntu.com/p/C7XY6w6ytK/

### bbstoper插件配置文件
https://paste.ubuntu.com/p/TKsVVhHnPY/

**Comment by R-Josef** [comment]
问题起因是当两种激励奖励的条件都不达成的时候，一个null的字符串导致的一个空指针异常，导致发放了奖励之后，不会写入数据库。这应该在接下来放出的3.6.1版本中修复。

**Comment by Xenon135** [comment]
感谢！
