### ISSUE TITLE
开服一段时间后会提示获取网页错误

### ISSUE THREAD

**Issue by JeskaiJet** [R-Josef/BBSToper#7]
每次刚开服的时候插件工作一切正常，但是过了一段时间之后（大概1小时）后台就会不断提示
**“[BBSToper] 获取网页时错误, 可能是由于网络波动!”**
之后就无法再检测到玩家的顶贴行为。

**Comment by R-Josef** [comment]
出现这种提示一般都是无法获取网页，你更改了自动奖励的间隔时间吗，如果改得太短有可能让mcbbs认为是攻击？你还可以尝试，当出现这个提示的时候，用服务器的浏览器看看你的宣传贴是否能够正常打开。
请把你的宣传贴id告诉我吧，我挂着试试看。

**Comment by JeskaiJet** [comment]
最开始是保持插件默认设置没有动，出现这个状况之后改成了间隔1分钟，仍然不能解决问题。我也认为可能是被MCBBS认为是在攻击。
是否可以更改插件的配置，取消自动奖励，来实现只有手动可以领取奖励？

**Comment by R-Josef** [comment]
可以，把自动奖励的间隔改成0，就关闭了自动奖励，希望这样能解决你的问题。

**Comment by R-Josef** [comment]
我先关闭了，如果你还有这个问题的话就请再打开这个issue
